import { companyInfo } from "@/database/database";
import styles from "./styles.module.scss";
import { Inter } from "next/font/google";
import '@/scss/main.scss';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <header className={styles.container} id="home">
        <div>{companyInfo.name}</div>
        <div className={styles.navigation}>
          <nav>
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#services">Services</a>
            <a href="#pages">Pages</a>
            <a href="#contact">Contact</a>
          </nav>
          <button>Get Started</button>
        </div>
      </header>
      <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
