import { companyInfo } from "@/database/database";
import styles from "./styles.module.scss"
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <div>{companyInfo.name}</div>
        <nav>
          <a href="">Home</a>
          <a href=""></a>About<a href="">Services</a>
          <a href="">Pages</a>
          <a href="">Contact</a>
        </nav>
        <button>Get Started</button>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
