"use client"
import { companyInfo } from "@/database/database";
import styles from "./styles.module.scss";
import { Inter } from "next/font/google";
import '@/scss/main.scss';
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [currentSection, setCurrentSection] = useState("")
  const sections = ["Home","About", "Services", "Pages", "Contact"]
  return (
    <html lang="en">
      <body>
      <header className={styles.container} id="home">
        <div className={styles.companyName}>{companyInfo.name}</div>
        <div className={styles.navigation}>
          <nav>
            {sections.map((section) => <a className={currentSection === section? styles.current:""} onClick={()=> setCurrentSection(section)} key={section}>{section}</a>)}
          </nav>
          <button>Get Started</button>
        </div>
      </header>
      <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
